version: "3"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/outageOutrage

  client:
    build: ./client
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
