import { Expertise, Role } from '../../types/types';

export const staffMembersInitialData = [
  {
    name: 'Alice',
    role: Role.FRONTEND_DEV,
    expertise: Expertise.JAVASCRIPT,
    ambition: 7,
    loyalty: 6,
    skillLevel: 8,
    resilience: 5,
    adaptability: 6,
    morale: 70,
    currentTask: null,
  },
  {
    name: 'Bob',
    role: Role.BACKEND_DEV,
    expertise: Expertise.PYTHON,
    ambition: 8,
    loyalty: 5,
    skillLevel: 7,
    resilience: 6,
    adaptability: 8,
    morale: 75,
    currentTask: null,
  },
  {
    name: 'Catherine',
    role: Role.QA,
    expertise: Expertise.SOFTWARE_TESTING,
    ambition: 5,
    loyalty: 7,
    skillLevel: 6,
    resilience: 8,
    adaptability: 7,
    morale: 60,
    currentTask: null,
  },
  {
    name: 'Dan',
    role: Role.PROJECT_MANAGER,
    expertise: Expertise.PROJECT_MANAGEMENT,
    ambition: 9,
    loyalty: 4,
    skillLevel: 9,
    resilience: 7,
    adaptability: 6,
    morale: 65,
    currentTask: null,
  },
  {
    name: 'Eva',
    role: Role.UX_UI_DESIGNER,
    expertise: Expertise.UX_DESIGN,
    ambition: 4,
    loyalty: 9,
    skillLevel: 6,
    resilience: 6,
    adaptability: 8,
    morale: 80,
    currentTask: null,
  },
  {
    name: 'Frank',
    role: Role.SECURITY_SPECIALIST,
    expertise: Expertise.CYBER_SECURITY,
    ambition: 8,
    loyalty: 5,
    skillLevel: 8,
    resilience: 9,
    adaptability: 6,
    morale: 70,
    currentTask: null,
  },
  {
    name: 'Grace',
    role: Role.BACKEND_DEV,
    expertise: Expertise.JAVA,
    ambition: 6,
    loyalty: 8,
    skillLevel: 7,
    resilience: 7,
    adaptability: 5,
    morale: 75,
    currentTask: null,
  },
  {
    name: 'Harry',
    role: Role.FRONTEND_DEV,
    expertise: Expertise.JAVASCRIPT,
    ambition: 7,
    loyalty: 7,
    skillLevel: 6,
    resilience: 8,
    adaptability: 7,
    morale: 60,
    currentTask: null,
  },
  {
    name: 'Isla',
    role: Role.QA,
    expertise: Expertise.SOFTWARE_TESTING,
    ambition: 5,
    loyalty: 9,
    skillLevel: 7,
    resilience: 7,
    adaptability: 6,
    morale: 85,
    currentTask: null,
  },
  {
    name: 'Jack',
    role: Role.PROJECT_MANAGER,
    expertise: Expertise.PROJECT_MANAGEMENT,
    ambition: 8,
    loyalty: 6,
    skillLevel: 8,
    resilience: 6,
    adaptability: 7,
    morale: 70,
    currentTask: null,
  },
];
