import { Expertise, Role } from '../../types/types';

export const staffMembersInitialData = [
  {
    name: 'Alice',
    role: Role.FRONTEND_DEV,
    expertise: Expertise.JAVASCRIPT,
    ambition: 7,
    loyalty: 6,
    skillLevel: 8,
    resilience: 5,
    adaptability: 6,
    morale: 70,
    currentTask: null,
  },
  {
    name: 'Bob',
    role: Role.BACKEND_DEV,
    expertise: Expertise.PYTHON,
    ambition: 8,
    loyalty: 5,
    skillLevel: 7,
    resilience: 6,
    adaptability: 8,
    morale: 75,
    currentTask: null,
  },
  {
    name: 'Catherine',
    role: Role.QA,
    expertise: Expertise.SOFTWARE_TESTING,
    ambition: 5,
    loyalty: 7,
    skillLevel: 6,
    resilience: 8,
    adaptability: 7,
    morale: 60,
    currentTask: null,
  },
  {
    name: 'Dan',
    role: Role.PROJECT_MANAGER,
    expertise: Expertise.PROJECT_MANAGEMENT,
    ambition: 9,
    loyalty: 4,
    skillLevel: 9,
    resilience: 7,
    adaptability: 6,
    morale: 65,
    currentTask: null,
  },
  {
    name: 'Eva',
    role: Role.UX_UI_DESIGNER,
    expertise: Expertise.UX_DESIGN,
    ambition: 4,
    loyalty: 9,
    skillLevel: 6,
    resilience: 6,
    adaptability: 8,
    morale: 80,
    currentTask: null,
  },
  {
    name: 'Frank',
    role: Role.SECURITY_SPECIALIST,
    expertise: Expertise.CYBER_SECURITY,
    ambition: 8,
    loyalty: 5,
    skillLevel: 8,
    resilience: 9,
    adaptability: 6,
    morale: 70,
    currentTask: null,
  },
  {
    name: 'Grace',
    role: Role.BACKEND_DEV,
    expertise: Expertise.JAVA,
    ambition: 6,
    loyalty: 8,
    skillLevel: 7,
    resilience: 7,
    adaptability: 5,
    morale: 75,
    currentTask: null,
  },
  {
    name: 'Harry',
    role: Role.FRONTEND_DEV,
    expertise: Expertise.JAVASCRIPT,
    ambition: 7,
    loyalty: 7,
    skillLevel: 6,
    resilience: 8,
    adaptability: 7,
    morale: 60,
    currentTask: null,
  },
  {
    name: 'Isla',
    role: Role.QA,
    expertise: Expertise.SOFTWARE_TESTING,
    ambition: 5,
    loyalty: 9,
    skillLevel: 7,
    resilience: 7,
    adaptability: 6,
    morale: 85,
    currentTask: null,
  },
  {
    name: 'Jack',
    role: Role.PROJECT_MANAGER,
    expertise: Expertise.PROJECT_MANAGEMENT,
    ambition: 8,
    loyalty: 6,
    skillLevel: 8,
    resilience: 6,
    adaptability: 7,
    morale: 70,
    currentTask: null,
  },
  {
    name: 'John Doe',
    role: Role.FRONTEND_DEV,
    expertise: 'Java',
    ambition: 10,
    loyalty: 100,
    skillLevel: 10,
    resilience: 10,
    adaptability: 10,
    morale: 100,
    currentTask: null,
  },
  {
    name: 'Jane Smith',
    role: Role.BACKEND_DEV,
    expertise: 'Python',
    ambition: 8,
    loyalty: 85,
    skillLevel: 8,
    resilience: 9,
    adaptability: 9,
    morale: 90,
    currentTask: null,
  },
  {
    name: 'Peter Williams',
    role: Role.QA,
    expertise: 'Software Testing',
    ambition: 7,
    loyalty: 80,
    skillLevel: 9,
    resilience: 8,
    adaptability: 7,
    morale: 85,
    currentTask: null,
  },
  {
    name: 'Sarah Johnson',
    role: Role.PROJECT_MANAGER,
    expertise: 'Project Management',
    ambition: 9,
    loyalty: 95,
    skillLevel: 7,
    resilience: 9,
    adaptability: 8,
    morale: 95,
    currentTask: null,
  },
  {
    name: 'Robert Davis',
    role: Role.UX_UI_DESIGNER,
    expertise: 'UX Design',
    ambition: 6,
    loyalty: 75,
    skillLevel: 8,
    resilience: 7,
    adaptability: 9,
    morale: 80,
    currentTask: null,
  },
  {
    name: 'Emma Thompson',
    role: Role.SECURITY_SPECIALIST,
    expertise: 'Cyber Security',
    ambition: 8,
    loyalty: 90,
    skillLevel: 9,
    resilience: 8,
    adaptability: 8,
    morale: 85,
    currentTask: null,
  },
];
