import { Expertise, ITask, TaskStatus, TaskType } from '../../types/types';

export const tasks: Partial<ITask>[] = [
  {
    id: '1',
    type: TaskType.BUG_FIX,
    complexity: 5,
    timeToComplete: 7,
    assignedTo: null,
    expertiseRequired: Expertise.JAVASCRIPT,
    criticality: 6,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '2',
    type: TaskType.NEW_FEATURE,
    complexity: 8,
    timeToComplete: 14,
    assignedTo: null,
    expertiseRequired: Expertise.PYTHON,
    criticality: 7,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '3',
    type: TaskType.SECURITY_PATCH,
    complexity: 9,
    timeToComplete: 10,
    assignedTo: null,
    expertiseRequired: Expertise.CYBER_SECURITY,
    criticality: 9,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '4',
    type: TaskType.BUG_FIX,
    complexity: 4,
    timeToComplete: 5,
    assignedTo: null,
    expertiseRequired: Expertise.JAVA,
    criticality: 5,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '5',
    type: TaskType.NEW_FEATURE,
    complexity: 7,
    timeToComplete: 15,
    assignedTo: null,
    expertiseRequired: Expertise.UX_DESIGN,
    criticality: 7,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '6',
    type: TaskType.SECURITY_PATCH,
    complexity: 8,
    timeToComplete: 12,
    assignedTo: null,
    expertiseRequired: Expertise.CYBER_SECURITY,
    criticality: 8,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '7',
    type: TaskType.BUG_FIX,
    complexity: 6,
    timeToComplete: 8,
    assignedTo: null,
    expertiseRequired: Expertise.JAVASCRIPT,
    criticality: 6,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '8',
    type: TaskType.NEW_FEATURE,
    complexity: 7,
    timeToComplete: 14,
    assignedTo: null,
    expertiseRequired: Expertise.PYTHON,
    criticality: 7,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '9',
    type: TaskType.SECURITY_PATCH,
    complexity: 9,
    timeToComplete: 13,
    assignedTo: null,
    expertiseRequired: Expertise.CYBER_SECURITY,
    criticality: 9,
    status: TaskStatus.NOT_STARTED,
  },
  {
    id: '10',
    type: TaskType.BUG_FIX,
    complexity: 5,
    timeToComplete: 6,
    assignedTo: null,
    expertiseRequired: Expertise.JAVA,
    criticality: 5,
    status: TaskStatus.NOT_STARTED,
  },
];
