name: Run Tests

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # adjust according to your project's Node.js version

      # Client-side tests
      - name: Install client dependencies
        run: cd client && npm install
      - name: Run client tests
        run: cd client && npm test

      # Server-side tests
      - name: Install server dependencies
        run: cd server && npm install
      - name: Run server tests
        run: cd server && npm test
